apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask-web-app
  name: flask-web-app-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-web-app
  type: NodePort
status:
  loadBalancer: {}
